tap "alecthomas/tap"
tap "caskroom/versions"
tap "caskroom/drivers"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "automake"
brew "aws-elasticbeanstalk"
brew "awscli"
brew "awslogs"
brew "certbot"
brew "coreutils"
brew "ctags"
brew "go"
brew "dep"
brew "geoip"
brew "git"
brew "gnupg"
brew "htop"
brew "jenv"
brew "jq"
brew "kubernetes-cli"
brew "kubernetes-helm"
brew "libiconv"
brew "libxml2"
brew "libyaml"
brew "mas"
brew "mysql"
brew "nmap"
brew "node"
brew "node@8"
brew "openssl@1.1"
brew "php"
brew "pkg-config"
brew "postgresql"
brew "python"
brew "python@2"
brew "serverless"
brew "sshuttle"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "adobe-acrobat-reader"
cask "alfred"
cask "appcleaner"
cask "aws-vault"
cask "battle-net"
cask "bit-slicer"
cask "bitbar"
cask "blitz"
cask "caffeine"
cask "cscreen"
cask "discord"
cask "docker"
cask "flux"
cask "flycut"
cask "gimp"
cask "google-backup-and-sync"
cask "google-chrome"
cask "intellij-idea-ce"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "league-of-legends"
cask "little-snitch"
# cask "logitech-options"
# cask "logitech-unifying"
cask "malwarebytes"
cask "microsoft-intellitype"
cask "microsoft-office"
cask "mysqlworkbench"
cask "nvidia-geforce-now"
cask "omnigraffle"
cask "postman"
cask "quickbooks-online"
cask "quicken"
cask "reflector"
cask "slack"
cask "spectacle"
cask "steam"
cask "teamviewer"
cask "tower"
cask "virtualbox"
cask "viscosity"
cask "visual-studio-code"
cask "xmind-zen"
mas "FileZilla", id: 1458095236
mas "Gifox", id: 1082624744
mas "Hazeover", id: 430798174
mas "iMovie", id: 408981434
mas "Lastpass", id: 926036361
mas "Microsoft Remote Desktop", id: 1295203466
mas "Notability", id: 736189492
mas "Kaspersky VPN", id: 1208561404
mas "Spark", id: 1176895641
